version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-174-129-18-42.compute-1.amazonaws.com
            database: d4cp3hfctess5p
            schema: public
            user: sclrghwzzdonyr
            password: 1a7b0c79bd0a989bcec5d29f48792e4290b83dbf88cf952dc611451f2e57a9a9
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true